[build-system]
requires = [
	"flit_core >=3.2,<4"
	]
build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[project]
name = "regression"
authors = [{name = "Ally Nicolella", email = "ally.nicolella@ucsf.edu"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "pytest", 
	"numpy",
	"pandas",
	"scikit-learn",
	"matplotlib" 
]
requires-python = ">=3.7"

[project.urls]
Home = "https://github.com/aanicolella/HW7-Regression.git"